# Daten einlesen

In [18]:
import pandas as pd

path_to_dataset = '02 Myocardial infarction complications Database.csv'

df = pd.read_csv(path_to_dataset) # evtl mit , sep=';'
df

,ID,AGE,SEX,INF_ANAM,STENOK_AN,FK_STENOK,IBS_POST,IBS_NASL,GB,SIM_GIPERT,...,JELUD_TAH,FIBR_JELUD,A_V_BLOK,OTEK_LANC,RAZRIV,DRESSLER,ZSN,REC_IM,P_IM_STEN,LET_IS
0,1,77.0,1,2.0,1.0,1.0,2.0,NaN,3.0,0.0,...,0,0,0,0,0,0,0,0,0,0
1,2,55.0,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
2,3,52.0,1,0.0,0.0,0.0,2.0,NaN,2.0,0.0,...,0,0,0,0,0,0,0,0,0,0
3,4,68.0,0,0.0,0.0,0.0,2.0,NaN,2.0,0.0,...,0,0,0,0,0,0,1,0,0,0
4,5,60.0,1,0.0,0.0,0.0,2.0,NaN,3.0,0.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1695,1696,77.0,0,0.0,4.0,2.0,1.0,NaN,2.0,0.0,...,0,0,1,0,1,0,0,0,0,3
1696,1697,70.0,0,0.0,6.0,2.0,1.0,NaN,2.0,0.0,...,0,0,0,0,0,0,0,0,0,1
1697,1698,55.0,1,3.0,6.0,2.0,2.0,NaN,0.0,0.0,...,0,0,0,0,0,0,0,1,0,6
1698,1699,79.0,0,2.0,2.0,2.0,1.0,NaN,2.0,0.0,...,0,0,0,1,0,0,0,0,0,1
1699,1700,63.0,1,2.0,NaN,NaN,NaN,NaN,2.0,0.0,...,0,0,0,0,0,0,0,0,0,1

## Modify dataset
### List all column names

In [19]:
print(df.columns.values)

['ID' 'AGE' 'SEX' 'INF_ANAM' 'STENOK_AN' 'FK_STENOK' 'IBS_POST' 'IBS_NASL'
 'GB' 'SIM_GIPERT' 'DLIT_AG' 'ZSN_A' 'nr_11' 'nr_01' 'nr_02' 'nr_03'
 'nr_04' 'nr_07' 'nr_08' 'np_01' 'np_04' 'np_05' 'np_07' 'np_08' 'np_09'
 'np_10' 'endocr_01' 'endocr_02' 'endocr_03' 'zab_leg_01' 'zab_leg_02'
 'zab_leg_03' 'zab_leg_04' 'zab_leg_06' 'S_AD_KBRIG' 'D_AD_KBRIG'
 'S_AD_ORIT' 'D_AD_ORIT' 'O_L_POST' 'K_SH_POST' 'MP_TP_POST' 'SVT_POST'
 'GT_POST' 'FIB_G_POST' 'ant_im' 'lat_im' 'inf_im' 'post_im' 'IM_PG_P'
 'ritm_ecg_p_01' 'ritm_ecg_p_02' 'ritm_ecg_p_04' 'ritm_ecg_p_06'
 'ritm_ecg_p_07' 'ritm_ecg_p_08' 'n_r_ecg_p_01' 'n_r_ecg_p_02'
 'n_r_ecg_p_03' 'n_r_ecg_p_04' 'n_r_ecg_p_05' 'n_r_ecg_p_06'
 'n_r_ecg_p_08' 'n_r_ecg_p_09' 'n_r_ecg_p_10' 'n_p_ecg_p_01'
 'n_p_ecg_p_03' 'n_p_ecg_p_04' 'n_p_ecg_p_05' 'n_p_ecg_p_06'
 'n_p_ecg_p_07' 'n_p_ecg_p_08' 'n_p_ecg_p_09' 'n_p_ecg_p_10'
 'n_p_ecg_p_11' 'n_p_ecg_p_12' 'fibr_ter_01' 'fibr_ter_02' 'fibr_ter_03'
 'fibr_ter_05' 'fibr_ter_06' 'fibr_ter_07' 'fibr_ter_08' 'GIPO_K'
 'K_BLOOD' 'GIPER_NA' 'NA_BLOOD' 'ALT_BLOOD' 'AST_BLOOD' 'KFK_BLOOD'
 'L_BLOOD' 'ROE' 'TIME_B_S' 'R_AB_1_n' 'R_AB_2_n' 'R_AB_3_n' 'NA_KB'
 'NOT_NA_KB' 'LID_KB' 'NITR_S' 'NA_R_1_n' 'NA_R_2_n' 'NA_R_3_n'
 'NOT_NA_1_n' 'NOT_NA_2_n' 'NOT_NA_3_n' 'LID_S_n' 'B_BLOK_S_n'
 'ANT_CA_S_n' 'GEPAR_S_n' 'ASP_S_n' 'TIKL_S_n' 'TRENT_S_n' 'FIBR_PREDS'
 'PREDS_TAH' 'JELUD_TAH' 'FIBR_JELUD' 'A_V_BLOK' 'OTEK_LANC' 'RAZRIV'
 'DRESSLER' 'ZSN' 'REC_IM' 'P_IM_STEN' 'LET_IS']

### Drop columns

In [20]:
y = df['ZSN']
X = df.drop('ZSN', axis=1)

### Train-test split

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

print(X_train.shape)

(1190, 123)

## EDA
### Overview

In [22]:
X_train.describe()

,ID,AGE,SEX,INF_ANAM,STENOK_AN,FK_STENOK,IBS_POST,IBS_NASL,GB,SIM_GIPERT,...,PREDS_TAH,JELUD_TAH,FIBR_JELUD,A_V_BLOK,OTEK_LANC,RAZRIV,DRESSLER,REC_IM,P_IM_STEN,LET_IS
count,1190.000000,1184.000000,1190.000000,1188.000000,1114.000000,1142.000000,1155.000000,50.000000,1182.000000,1183.000000,...,1190.000000,1190.000000,1190.000000,1190.000000,1190.000000,1190.000000,1190.000000,1190.000000,1190.000000,1190.000000
mean,845.112605,61.869932,0.615966,0.552189,2.364452,1.250438,1.183550,0.400000,1.436548,0.035503,...,0.012605,0.027731,0.038655,0.033613,0.100000,0.031933,0.038655,0.098319,0.086555,0.460504
std,492.112611,11.315202,0.486570,0.832048,2.428128,1.036737,0.791576,0.494872,1.083609,0.185126,...,0.111609,0.164270,0.192853,0.180308,0.300126,0.175895,0.192853,0.297871,0.281300,1.345848
min,1.000000,26.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,419.250000,54.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,851.500000,63.000000,1.000000,0.000000,2.000000,2.000000,1.000000,0.000000,2.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1259.500000,70.000000,1.000000,1.000000,5.000000,2.000000,2.000000,1.000000,2.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1700.000000,92.000000,1.000000,3.000000,6.000000,4.000000,2.000000,1.000000,3.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,7.000000

### List missing values by column

In [23]:
# Check for missing values
missing_values = df.isnull().sum()
columns = df.columns
print("Missing values in each column:")
for col, missing in zip(columns, missing_values):
    print(f"{col}: {missing}")

Missing values in each column:
ID: 0
AGE: 8
SEX: 0
INF_ANAM: 4
STENOK_AN: 106
FK_STENOK: 73
IBS_POST: 51
IBS_NASL: 1628
GB: 9
SIM_GIPERT: 8
DLIT_AG: 248
ZSN_A: 54
nr_11: 21
nr_01: 21
nr_02: 21
nr_03: 21
nr_04: 21
nr_07: 21
nr_08: 21
np_01: 18
np_04: 18
np_05: 18
np_07: 18
np_08: 18
np_09: 18
np_10: 18
endocr_01: 11
endocr_02: 10
endocr_03: 10
zab_leg_01: 7
zab_leg_02: 7
zab_leg_03: 7
zab_leg_04: 7
zab_leg_06: 7
S_AD_KBRIG: 1076
D_AD_KBRIG: 1076
S_AD_ORIT: 267
D_AD_ORIT: 267
O_L_POST: 12
K_SH_POST: 15
MP_TP_POST: 14
SVT_POST: 12
GT_POST: 12
FIB_G_POST: 12
ant_im: 83
lat_im: 80
inf_im: 80
post_im: 72
IM_PG_P: 1
ritm_ecg_p_01: 152
ritm_ecg_p_02: 152
ritm_ecg_p_04: 152
ritm_ecg_p_06: 152
ritm_ecg_p_07: 152
ritm_ecg_p_08: 152
n_r_ecg_p_01: 115
n_r_ecg_p_02: 115
n_r_ecg_p_03: 115
n_r_ecg_p_04: 115
n_r_ecg_p_05: 115
n_r_ecg_p_06: 115
n_r_ecg_p_08: 115
n_r_ecg_p_09: 115
n_r_ecg_p_10: 115
n_p_ecg_p_01: 115
n_p_ecg_p_03: 115
n_p_ecg_p_04: 115
n_p_ecg_p_05: 115
n_p_ecg_p_06: 115
n_p_ecg_p_07: 115
n_p_ecg_p_08: 115
n_p_ecg_p_09: 115
n_p_ecg_p_10: 115
n_p_ecg_p_11: 115
n_p_ecg_p_12: 115
fibr_ter_01: 10
fibr_ter_02: 10
fibr_ter_03: 10
fibr_ter_05: 10
fibr_ter_06: 10
fibr_ter_07: 10
fibr_ter_08: 10
GIPO_K: 369
K_BLOOD: 371
GIPER_NA: 375
NA_BLOOD: 375
ALT_BLOOD: 284
AST_BLOOD: 285
KFK_BLOOD: 1696
L_BLOOD: 125
ROE: 203
TIME_B_S: 126
R_AB_1_n: 16
R_AB_2_n: 108
R_AB_3_n: 128
NA_KB: 657
NOT_NA_KB: 686
LID_KB: 677
NITR_S: 9
NA_R_1_n: 5
NA_R_2_n: 108
NA_R_3_n: 131
NOT_NA_1_n: 10
NOT_NA_2_n: 110
NOT_NA_3_n: 131
LID_S_n: 10
B_BLOK_S_n: 11
ANT_CA_S_n: 13
GEPAR_S_n: 17
ASP_S_n: 17
TIKL_S_n: 16
TRENT_S_n: 16
FIBR_PREDS: 0
PREDS_TAH: 0
JELUD_TAH: 0
FIBR_JELUD: 0
A_V_BLOK: 0
OTEK_LANC: 0
RAZRIV: 0
DRESSLER: 0
ZSN: 0
REC_IM: 0
P_IM_STEN: 0
LET_IS: 0

## Standardization

In [24]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_train = pd.DataFrame(X_train_scaled, columns=X_train.columns)
X_test_scaled = scaler.transform(X_test)
X_test = pd.DataFrame(X_test_scaled, columns=X_train.columns)

## Nan-value imputation
### Simple imputation

In [25]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='constant', fill_value=0)
# Possibilities: 'mean', 'median', 'most_frequent', 'constant'
X_train_imputed = imputer.fit_transform(X_train)
X_train = pd.DataFrame(X_train_imputed, columns=X_train.columns)
X_test = imputer.transform(X_test)
X_test = pd.DataFrame(X_test, columns=X_train.columns)

### KNN imputation

In [26]:
from sklearn.impute import KNNImputer

imputer = KNNImputer(n_neighbors=5)
X_train_imputed = imputer.fit_transform(X_train)
X_train = pd.DataFrame(X_train_imputed, columns=X_train.columns)
X_test = imputer.transform(X_test)
X_test = pd.DataFrame(X_test, columns=X_train.columns)

## Models
### Linear regression

In [31]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)

# Explanation of coefficients
coefficients = model.coef_
feature_names = X_train.columns

# Sort by absolute coefficient value (descending)
features_and_coefficients = sorted(
    zip(feature_names, coefficients),
    key=lambda x: abs(x[1]),
    reverse=True
)

print("Top 10 features by absolute coefficient value:")
for feature, coefficient in features_and_coefficients[:10]:
    print(f"{feature}: {coefficient:.4f}")

Top 10 features by absolute coefficient value:
KFK_BLOOD: 0.2766
ID: -0.1058
ZSN_A: 0.0579
FIBR_PREDS: 0.0576
DRESSLER: 0.0528
lat_im: 0.0508
n_r_ecg_p_06: 0.0465
zab_leg_01: 0.0453
D_AD_ORIT: -0.0449
S_AD_ORIT: 0.0415